### ISSUE TITLE
Suggestion: link to R's gemma2?

### ISSUE THREAD

**Issue by richelbilderbeek** [genetics-statistics/GEMMA#246]
Here I suggest to add a link to [https://github.com/fboehm/gemma2](https://github.com/fboehm/gemma2) in the README.md

GEMMA is a great CLI tool. Some people, however, prefer to work from R. At #35 there was the question to add an R wrapper around GEMMA. I found @fboehm rewrote GEMMA for R and posted his code at [https://github.com/fboehm/gemma2](https://github.com/fboehm/gemma2). That there is an existing R version of GEMMA would interest R users.

I suggest to add a link to [https://github.com/fboehm/gemma2](https://github.com/fboehm/gemma2) in the README.md. 

Sure, I do volunteer to do so using a Fork and PR to the `dev` branch :+1:

**Comment by pjotrp** [comment]
Gemma2, despite its name is not a full implementation of GEMMA. Feel free to report your findings here.

**Comment by richelbilderbeek** [comment]
Agreed! And I don't have a question about either GEMMA or GEMMA2. I only suggest to link to that partial R implementation. I feel that would be fair to the implementer of GEMMA2.

**Comment by pjotrp** [comment]
I am hesitant to add it to the docs because the GEMMA2 implementation is not complete, probably quite a bit slower, and actually differs even for the LMM (as the author states). The project should really have been called R/gemma or something because is not even a match for GEMMAv1. I think it is fine the link is recorded here in the issue tracker. If anyone does a real comparison I am happy to add that to the docs. That is compare coverage, input, output and execution metrics. Maybe I'll get round to it at some point.

**Comment by richelbilderbeek** [comment]
I feel you. I just also feel the GAMMA2 R person being underappreciated (as in: what would you enjoy would you be him/her?). [I know I did my share of linking myself as well, to things I may not fully agree with](https://github.com/ropensci/beautier/blob/master/doc/faq.md#are-there-any-related-packages), and I feel that is a good thing.

Well, in the end you are boss, so I will agree with whatever you choose, e.g. closing this Issue! 

Keep up the good work and cheers, Richel

**Comment by richelbilderbeek** [comment]
Feels like it is time to close this Issue :+1:
