### ISSUE TITLE
Testing with covariates got errors "gsl: brent.c:202: ERROR: function value is not finite"

### ISSUE THREAD

**Issue by Owen-haha** [genetics-statistics/GEMMA#57]
When try to test a SNP's association with phenotype by putting a bunch of other SNPs as covariates, returning the errors **"gsl: brent.c:202: ERROR: function value is not finite".** 
Assuming there are 4 SNPs in total, SNP0, SNP1, SNP2 and SNP3.
The model likes this: Y ~ alpha1 *  SNP1 + alpha2 * SNP2 + alpha3 * SNP3 + beta * SNP0 + u + e
where SNP0 is the SNP being tested, and SNP1, SNP2 and SNP3 are covariates.
SNP0, SNP1, SNP2 and SNP3 could have high correlation with each other, say r2 > 0.6.
The relatedness matrix is calculated by using all the SNPs available, say SNP0, SNP1, SNP2 and SNP3. 
Has  anyone tried to do something like this?  How to figure out the infinite problem?

**Comment by pcarbo** [comment]
Hi @Owen-haha, can you please give the exact `gemma` command you used? Do you get the same error if you do not include the polygenic term `u` (that is, you use the `-lm` option)? Are SNP1 –4 also being tested, or did you remove them from the genotype data file?

**Comment by Owen-haha** [comment]
Hi @pcarbo , below is the command i run. I also attached a real sample here. 
`gemma.0.93b -g gen_file.txt -p pheno_file.txt -a snp_info_file.txt -k realmatrix_file.txt -lmm 4 -o prefix -maf 0 -c cov_file.txt`
[gen_file.TXT](https://github.com/genetics-statistics/GEMMA/files/1151449/gen_file.TXT)
[pheno_file.txt](https://github.com/genetics-statistics/GEMMA/files/1151450/pheno_file.txt)
[snp_info_file.txt](https://github.com/genetics-statistics/GEMMA/files/1151451/snp_info_file.txt)
[realmatrix_file.txt.zip](https://github.com/genetics-statistics/GEMMA/files/1151455/realmatrix_file.txt.zip)
[cov_file.txt](https://github.com/genetics-statistics/GEMMA/files/1151452/cov_file.txt)
I cannot do `-lm` because the version i used dose not support it. 
There is only one SNP in gen_file.txt, and 9 covariates in cov_file.txt. And the SNPs in gen_file.txt and cov_file.txt are excluded. Each time only tests one SNP.

**Comment by pcarbo** [comment]
@Owen-haha I would encourage you to download the [latest version of GEMMA](https://github.com/genetics-statistics/GEMMA/releases). Please let me know if you have trouble getting it to work.

Second, I would recommend starting with a simpler association analysis such as this:

```
./gemma -g gen_file.txt -p pheno_file.txt -lm 2 -maf 0
```

You will find that the results aren't very interesting for your particular example because there is very little variation in the SNP you are testing; the minor allele is observed only once among the ~1,500 samples. Regression coefficient estimates in this sort of case aren't well behaved. I would suggest that you remove SNPs such as this that exhibit very little variation in your sample.
