### ISSUE TITLE
Inflated p-values using GEMMA on haploid organisms?

### ISSUE THREAD

**Issue by thorellk** [genetics-statistics/GEMMA#77]
Dear Pjotr and Xiang,

We have been running GEMMA on bacterial data, attempting to find epistatic interactions by encoding the alleles at one of the loci as a phenotype and testing its interaction with the other locus. The answers that GEMMA gives are correlated with the truth, but appear to have widely inflated significance values. Another noticeable feature is that for many loci p_score is much less inflated than p_wald or p_lrt. There is also a hint that values are most inflated for low-frequency variants. For example, one locus with 5 1s and 265 0s is associated with another locus with 3 1s and 268 0s, where the 3 1s at the second locus all match with 1s at the first. GEMMA as we run it gives a p value of 10^-31 for the Wald and LRT, with 10^-21 for the score test when a sensible value would be around 10^-6.

We are guessing there is some systematic error in how the data is being interpreted, which probably reflects a misunderstanding of input format or suchlike. The command line we are running currently looks like this:

```gemma -g genfile_gemma.txt -p phenotype_general.txt -a snpfile_gemma.txt -gk 1 -o rel_matrix -maf 0```

```gemma -g genfile_gemma.txt -p $locus_pheno.txt -a snpfile_gemma.txt -k rel_matrix.cXX.txt -lmm 4 -o $locus -maf 0```

We have marked in the snp file that all positions are at chromosome 24 (y-chrom), which we understood is the suggestion for haploid organisms.

Obviously we are happy to send the data files on request.  Any idea what could be going wrong?  All suggestions much appreciated.  Looking forward to figuring this out! 

Best,

Kaisa

**Comment by pcarbo** [comment]
@thorellk This sounds like very interesting work. 

When possible, I recommend using the likelihood ratio test (`-lmm 2`), which does not make as many approximations as the other tests (e.g., Wald, score).

There are many possible explanations for the behaviour you are observing---it would be difficult to pinpoint the cause here. One likely explanations is that you have "outliers" in your data set; that is, extremely small or extremely large phenotype values that could artificially inflate the evidence for association, especially for variants with low MAF. In [this manuscript](http://dx.doi.org/10.1038/ng.3609) we used GEMMA for all our association analyses and we took several steps to make sure that outliers were removed and that the distribution of the phenotype residuals looked roughly "normal".

**Comment by thorellk** [comment]
Thanks a lot for your fast reply @pcarbo!

I reran starting by filtering out everything with an allele frequency of < 2% and the results looks much more reasonable and even more when increasing the cutoff to 5%. We will now increase the sample size and rerun and even more look into the distribution of phenotypes and removal of outliers for that dataset. Also, we can limit our testing to the -lmm 2 as you suggested, thank you!

**Comment by pcarbo** [comment]
@thorellk Sounds good, thanks for sharing!
