### ISSUE TITLE
 GEMMA gwas results ,the p_value is different

### ISSUE THREAD

**Issue by Huangyizhong** [genetics-statistics/GEMMA#86]
Hello:
   These days I use the GEMMA software to do the Genome-wide association study, the model is Univariate Linear Mixed Model .We use the same genotype and  phenotype following the same codes. But p_value of p_wald is different, though the top snp name is same one. I have checked centered relatedness matrix is different. But why? Sorry to disturb！
Thanks

**Comment by pcarbo** [comment]
@Huangyizhong I'm glad to hear that you are finding GEMMA useful. 

The likelihood ratio test *p*-value is generally preferred over the Wald because it makes fewer approximations. Use `-lmm 2` to compute these *p*-values.

There are different ways to compute the relatedness matrix. Please see p. 19 of the manual for details on this.

I'm not quite sure I understand your question---if you provide me with more details about the GEMMA command that you ran, I can try to answer your question more precisely.

**Comment by Huangyizhong** [comment]
Glad to receive the answer from you and sorry to reply so late. I had found the reason  why the p value of p_wald was different among other people with the same data.Because they used  variant edition of plink software to control the genotype! 
 Thanks again
 sincerely!

**Comment by pcarbo** [comment]
@Huangyizhong Thanks for the update.
