### ISSUE TITLE
Multithreading gemma?

### ISSUE THREAD

**Issue by thorellk** [genetics-statistics/GEMMA#91]
Hi!

Is there any way of getting gemma to efficiently utilize e.g. a 16 core system?

Best wishes,

Kaisa

**Comment by pcarbo** [comment]
@thorellk Yes, but you would have to build GEMMA from source. I recommend linking to [OpenBLAS](http://github.com/xianyi/OpenBLAS). What operating system are you using? Let us know if you need help with configuring the Makefile.

**Comment by thorellk** [comment]
Thanks @pcarbo, I am working on this computational cluster http://www.uppmax.uu.se/resources/systems/the-milou-cluster/ What specs would you need to know?

**Comment by pcarbo** [comment]
@thorellk Great, that is actually quite similar to the [U of C compute cluster](https://rcc.uchicago.edu/docs/using-midway/#types-of-compute-nodes). To start, you should find out whether the required libraries (GSL, OpenBLAS / ATLAS / Intel MKL) are installed on the cluster, and find their locations. And you also need to locate a suitable version of gcc & gfortran. See [here](https://github.com/genetics-statistics/GEMMA/blob/master/INSTALL.md) for details. You might need the sys admin's guidance with some of these steps.

**Comment by pcarbo** [comment]
@thorellk You will also need to change some of the variables in the Makefile so that `gcc` is able to find these libraries on your system.

**Comment by thorellk** [comment]
Thank you @pcarbo, I will check up those details!

**Comment by pjotrp** [comment]
OpenBLAS solves part of the problem. We are actually working on a faster GEMMA. It is a work in progress. More later this year, I hope.

**Comment by thorellk** [comment]
@pcarbo: We do have OpenBLAS v 0.2.19, ATLAS, and gsl v 2.3 installed as a modules on the server. Would you recommend me installing the last stable version or the development version?

@pjotrp: Nice to hear, looking forward :)

**Comment by pcarbo** [comment]
@thorellk Great. I would start with the most recent stable release (v0.96) since the issues are better known, but know that we will soon have a new stable release (0.97). Let us know if you need advice modifying the `Makefile`. You make find it useful to consult the `Makefile.linux` file, which was used to build GEMMA on the U of C compute cluster (also using modules), but be warned this Makefile is out-of-date so you should not use it directly.

**Comment by thorellk** [comment]
Yes, it would be really helpful to get some advice for the Makefile configuration @pcarbo

**Comment by pcarbo** [comment]
@thorellk The main change you will need to make is to add `-I` and `-L` flags to variable `GCC_FLAGS` so that the compiler knows where to find the BLAS & GSL library and include files. Do you know where the BLAS (e.g., ATLAS) and GSL libraries are found on the compute cluster? Your sys admin may be able to help with this (or perhaps there are GSL & ATLAS modules). Also, you will need to find out what version of gcc was used to compile these libraries.

**Comment by pjotrp** [comment]
Also read INSTALL.md. It is all there. https://github.com/genetics-statistics/GEMMA/blob/master/INSTALL.md

**Comment by pjotrp** [comment]
Try the latest release https://groups.google.com/forum/#!topic/gemma-discussion/2NPWKhh3ixE

**Comment by dgarrimar** [comment]
Is multithreading for kinship calculation the default in the latest version available through conda (0.98.1)?
